version: "3"
services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest # 镜像版本
    ports:
      - 3000:3000 # 暴露端口
    volumes: # 挂载
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:5.7.27
    ports:
      - 3306:3306
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=yourpassword
  redis:
    image: redis:6.2.6
    container_name: my-redis
    restart: always,
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass yourpassword
    volumes:
      - /root/redis/cache:/data
  react_admin:
    image: admin:latest
    container_name: react_admin_backend
    build: . #
    ports:
      - 8080:8080
    depends_on: # 依赖与mysql、redis，其实可以不填，默认已经表示可以
      - mysql
      - redis
